@PORT = 3000
@HOST = http://localhost:{{PORT}}

GET {{HOST}}/api/groups/13
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxMSwiZXhwIjoxNzE1NzA3MTIzLCJpYXQiOjE3MTU3MDY4MjN9.fNFTXAxIsqANtmX-h2tbFLzmQAevUBejC21Q_IaX0o4

###
GET {{HOST}}/api/groups/group/1

###
GET {{HOST}}/api/groups/users/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxMSwiZXhwIjoxNzE1Njk5Mzg3LCJpYXQiOjE3MTU2OTkwODd9.xtirDdja6SeVZKKx-vD5eu2cVfAHRcmayTESV9aMcNs

###     
POST {{HOST}}/api/groups/
Content-Type: application/json

{
    "nombre": "Comida de empresa 2023",
    "descripcion": "Comida de empresa con compañeros en Valencia"
}

###
POST {{HOST}}/api/groups/user
Content-Type: application/json

{
    "idGrupo": 3,
    "idUsuario": 18,
    "porcentaje": 100,
    "rol": "admin"
}

###
DELETE {{HOST}}/api/groups/15

###
GET {{HOST}}/api/users/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxMSwiZXhwIjoxNzE1NzAxMTUxLCJpYXQiOjE3MTU3MDA4NTF9.gw1jSP6riOmj7Qx36ITsSirHZdxfG2FuxdKL-uyPI2A

###
POST {{HOST}}/api/users/register
Content-Type: application/json

{
    "nombre": "Laura",
    "apellidos": "Diaz Fernandez",
    "email": "laura.diaz@gmail.com",
    "password": "12345",
    "imagen": "foto_usuario.png"
}

###
POST {{HOST}}/api/users/login
Content-Type: application/json

{
    "email": "sonia.fernandez@gmail.com",
    "password": "12345"
}

###
GET {{HOST}}/api/spents/2

###
GET {{HOST}}/api/spents/total/1

###
GET {{HOST}}/api/spents/saldos/1

###
POST {{HOST}}/api/spents/
Content-Type: application/json

{
    "idUsuario": 1,
    "idGrupo": 1,
    "descripcion": "regalo",
    "importe": 46,
    "fecha": "2024-02-18"
}

###
PUT {{HOST}}/api/spents/4
Content-Type: application/json

{
    "idGrupo": 1,
    "idUsuario": 1,
    "importe": 46,
    "descripcion": "regalo",
    "fecha": "2024-02-18"
}

